---
apiVersion: v1
kind: ConfigMap
metadata:
  name: valid-api-client-envoy-config
data:
  envoy.yaml: |
    admin:
      access_log_path: /var/log/envoy_admin_access.log
      address:
        socket_address:
          address: 0.0.0.0
          port_value: 9901
    node:
      id: "id_01"
      cluster: "cluster_01"
    static_resources:
      listeners:
      - name: mtls-listener-requesting-api
        address:
          socket_address:
            address: 127.0.0.1
            port_value: 8000
        filter_chains:
        - filters:
          - name: envoy.http_connection_manager
            config:
              idle_timeout: 1s
              forward_client_cert_details: sanitize_set
              set_current_client_cert_details:
                  uri: true
              codec_type: auto
              access_log:
              - name: envoy.file_access_log
                config:
                  path: "/var/log/envoy_access.log"
              stat_prefix: ingress_http
              route_config:
                name: local_route
                virtual_hosts:
                - name: local_service
                  domains: ["*"]
                  routes:
                  - match:
                      prefix: "/"
                    route:
                      cluster: requesting-api
              http_filters:
              - name: envoy.router
      clusters:
      - name: spire_agent
        connect_timeout: 0.25s
        http2_protocol_options: {}
        hosts:
          - pipe:
              path: /run/spire/sockets/agent.sock
      - name: requesting-api
        connect_timeout: 0.25s
        type: strict_dns
        lb_policy: ROUND_ROBIN
        hosts:
          - socket_address:
              address: api
              port_value: 8000
        tls_context:
          common_tls_context:
            tls_certificate_sds_secret_configs:
              - name: "spiffe://example.org/valid-api-client"
                sds_config:
                  api_config_source:
                    api_type: GRPC
                    grpc_services:
                      envoy_grpc:
                        cluster_name: spire_agent
            combined_validation_context:
              default_validation_context:
                verify_subject_alt_name:
                  - "spiffe://example.org/api"
              validation_context_sds_secret_config:
                name: "spiffe://example.org"
                sds_config:
                  api_config_source:
                    api_type: GRPC
                    grpc_services:
                      envoy_grpc:
                        cluster_name: spire_agent
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: valid-api-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: valid-api-client
  template:
    metadata:
      labels:
        app: valid-api-client
    spec:
      containers:
        - name: envoy
          image: envoyproxy/envoy:v1.11.1
          command: ["/usr/local/bin/envoy"]
          args: ["--config-path","/etc/envoy/envoy.yaml"]
          ports:
          - containerPort: 8000
          volumeMounts:
            - name: valid-api-client-envoy-config
              mountPath: /etc/envoy
              readOnly: true
            - name: spire-agent-socket
              mountPath: /run/spire/sockets
              readOnly: true
        - name: curl
          image: pstauffer/curl:v1.0.3
          command: ["sleep"]
          args: ["10000000"]
      volumes:
        - name: valid-api-client-envoy-config
          configMap:
            name: valid-api-client-envoy-config
        - name: spire-agent-socket
          hostPath:
            path: /run/spire/sockets
            type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: valid-api-client
spec:
  type: NodePort
  ports:
    - name: envoy-admin-port
      port: 9901
      targetPort: 9901
  selector:
    app: valid-api-client
